---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: run
  image: alpine
  commands:
  - echo "Hello how are you. yess"

- name: run_1
  image: alpine
  commands:
  - echo "I am fine ss hehehe"
