---
kind: pipeline
# type: docker
name: Run Pipeline

platform:
  os: linux
  arch: amd64
  
steps:
- name: Run Step
  image: alpine
  commands:
  - echo "Hello how r u. Yes i am fine"


trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**   

